package:
    name: cam_server_client
    version: 3.8.1

source:
    path: ..

requirements:
  build:
      - python
  run:
      - python
      - requests
      - bsread >1.5.0
      - bitshuffle >=0.3.6.1

build:
  number: 0

about:
    home: https://github.com/paulscherrerinstitute/cam_server
