- hosts: cam_server
  become: true
  tasks:
    - name: Reload systemd Config
      shell: |
        systemctl daemon-reload


    - name: Rertart services
      shell: |
        systemctl restart camera_worker pipeline_worker