- hosts: cam_manager
  become: true
  tasks:
    - name: stop pipeline_manager service
      systemd:
        name: pipeline_manager
        state: stopped

    - name: stop camera_manager service
      systemd:
        name: camera_manager
        state: stopped


- hosts: cam_workers
  become: true
  tasks:
    - name: stop pipeline_worker service
      systemd:
        name: pipeline_worker
        state: stopped

    - name: stop camera_worker service
      systemd:
        name: camera_worker
        state: stopped
