- hosts: cam_server
  become: true
  tasks:
  - name: stop pipeline_worker service
    systemd: 
      name: pipeline_worker 
      state: stopped

  - name: stop camera_worker service
    systemd: 
      name: camera_worker 
      state: stopped



    